$(document).ready(function(){
    $("#menuInicio").click(function(event){
        $("#divInicio").show(1000);
        $("#divtrabajosequipoC1").hide(1000);
        $("#divtrabajosLuisC1").hide(1000);
        $("#divtrabajosLaloC1").hide(1000);
        $("#divtrabajosChoryC1").hide(1000);
        $("#divtrabajosAlexC1").hide(1000);
        //C2
        $("#divtrabajosequipoC2").hide(1000);
        $("#divtrabajosLuisC2").hide(1000);
        $("#divtrabajosLaloC2").hide(1000);
        $("#divtrabajosChoryC2").hide(1000);
        $("#divtrabajosAlexC2").hide(1000);
        //conferencias
        $("##menuConferencias").hide(1000);
    });
    $("#menuTrabajdosEquipoC1").click(function(event){
        $("#divtrabajosequipoC1").show(1000);
        $("#divtrabajosLuisC1").hide(1000);
        $("#divtrabajosLaloC1").hide(1000);
        $("#divtrabajosChoryC1").hide(1000);
        $("#divtrabajosAlexC1").hide(1000);
        $("#divInicio").hide("slow");
        //C2
        $("#divtrabajosequipoC2").hide(1000);
        $("#divtrabajosLuisC2").hide(1000);
        $("#divtrabajosLaloC2").hide(1000);
        $("#divtrabajosChoryC2").hide(1000);
        $("#divtrabajosAlexC2").hide(1000);

         //conferencias
        $("##menuConferencias").hide(1000);
        
    });
    $("#menuLuisC1").click(function(event){
        $("#divtrabajosLuisC1").show(1000);
        $("#divtrabajosequipoC1").hide(1000);
        $("#divtrabajosLaloC1").hide(1000);
        $("#divtrabajosChoryC1").hide(1000);
        $("#divtrabajosAlexC1").hide(1000);
        $("#divInicio").hide("slow");
        //C2
        $("#divtrabajosequipoC2").hide(1000);
        $("#divtrabajosLuisC2").hide(1000);
        $("#divtrabajosLaloC2").hide(1000);
        $("#divtrabajosChoryC2").hide(1000);
        $("#divtrabajosAlexC2").hide(1000);

        //conferencias
        $("##menuConferencias").hide(1000);
    });
    $("#menuLaloC1").click(function(event){
        $("#divtrabajosLaloC1").show(1000);
        $("#divtrabajosLuisC1").hide(1000);
        $("#divtrabajosequipoC1").hide(1000);
        $("#divtrabajosChoryC1").hide(1000);
        $("#divtrabajosAlexC1").hide(1000);
        $("#divInicio").hide("slow");
        //C2
        $("#divtrabajosequipoC2").hide(1000);
        $("#divtrabajosLuisC2").hide(1000);
        $("#divtrabajosLaloC2").hide(1000);
        $("#divtrabajosChoryC2").hide(1000);
        $("#divtrabajosAlexC2").hide(1000);

        //conferencias
        $("##menuConferencias").hide(1000);
    });
    $("#menuChoryC1").click(function(event){
        $("#divtrabajosChoryC1").show(1000);
        $("#divtrabajosLaloC1").hide(1000);
        $("#divtrabajosLuisC1").hide(1000);
        $("#divtrabajosequipoC1").hide(1000);
        $("#divtrabajosAlexC1").hide(1000);
        $("#divInicio").hide("slow");
        //C2
        $("#divtrabajosequipoC2").hide(1000);
        $("#divtrabajosLuisC2").hide(1000);
        $("#divtrabajosLaloC2").hide(1000);
        $("#divtrabajosChoryC2").hide(1000);
        $("#divtrabajosAlexC2").hide(1000);

        //conferencias
        $("##menuConferencias").hide(1000);
    });
    $("#menuAlexC1").click(function(event){
        $("#divtrabajosAlexC1").show(1000);
        $("#divtrabajosChoryC1").hide(1000);
        $("#divtrabajosLaloC1").hide(1000);
        $("#divtrabajosLuisC1").hide(1000);
        $("#divtrabajosequipoC1").hide(1000);
        $("#divInicio").hide("slow");
        //C2
        $("#divtrabajosequipoC2").hide(1000);
        $("#divtrabajosLuisC2").hide(1000);
        $("#divtrabajosLaloC2").hide(1000);
        $("#divtrabajosChoryC2").hide(1000);
        $("#divtrabajosAlexC2").hide(1000);   
    });
    $("#menuTrabajdosEquipoC2").click(function(event){
        //C1
        $("#divtrabajosAlexC1").hide(1000);
        $("#divtrabajosChoryC1").hide(1000);
        $("#divtrabajosLaloC1").hide(1000);
        $("#divtrabajosLuisC1").hide(1000);
        $("#divtrabajosequipoC1").hide(1000);
        $("#divInicio").hide("slow");
        //C2
        $("#divtrabajosequipoC2").show(1000);
        $("#divtrabajosLuisC2").hide(1000);
        $("#divtrabajosLaloC2").hide(1000);
        $("#divtrabajosChoryC2").hide(1000);
        $("#divtrabajosAlexC2").hide(1000);
    });
        $("#menuLuisC2").click(function(event){
        $("#divtrabajosLuisC1").hide(1000);
        $("#divtrabajosequipoC1").hide(1000);
        $("#divtrabajosLaloC1").hide(1000);
        $("#divtrabajosChoryC1").hide(1000);
        $("#divtrabajosAlexC1").hide(1000);
        $("#divInicio").hide("slow");
        //C2
        $("#divtrabajosequipoC2").hide(1000);
        $("#divtrabajosLuisC2").show(1000);
        $("#divtrabajosLaloC2").hide(1000);
        $("#divtrabajosChoryC2").hide(1000);
        $("#divtrabajosAlexC2").hide(1000);
    });
    $("#menuLaloC2").click(function(event){
        $("#divtrabajosLaloC1").hide(1000);
        $("#divtrabajosLuisC1").hide(1000);
        $("#divtrabajosequipoC1").hide(1000);
        $("#divtrabajosChoryC1").hide(1000);
        $("#divtrabajosAlexC1").hide(1000);
        $("#divInicio").hide("slow");
        //C2
        $("#divtrabajosequipoC2").hide(1000);
        $("#divtrabajosLuisC2").hide(1000);
        $("#divtrabajosLaloC2").show(1000);
        $("#divtrabajosChoryC2").hide(1000);
        $("#divtrabajosAlexC2").hide(1000);
    });
    $("#menuChoryC2").click(function(event){
        $("#divtrabajosChoryC1").hide(1000);
        $("#divtrabajosLaloC1").hide(1000);
        $("#divtrabajosLuisC1").hide(1000);
        $("#divtrabajosequipoC1").hide(1000);
        $("#divtrabajosAlexC1").hide(1000);
        $("#divInicio").hide("slow");
        //C2
        $("#divtrabajosequipoC2").hide(1000);
        $("#divtrabajosLuisC2").hide(1000);
        $("#divtrabajosLaloC2").hide(1000);
        $("#divtrabajosChoryC2").show(1000);
        $("#divtrabajosAlexC2").hide(1000);
    });
    $("#menuAlexC2").click(function(event){
        $("#divtrabajosAlexC1").hide(1000);
        $("#divtrabajosChoryC1").hide(1000);
        $("#divtrabajosLaloC1").hide(1000);
        $("#divtrabajosLuisC1").hide(1000);
        $("#divtrabajosequipoC1").hide(1000);
        $("#divInicio").hide("slow");
        //C2
        $("#divtrabajosequipoC2").hide(1000);
        $("#divtrabajosLuisC2").hide(1000);
        $("#divtrabajosLaloC2").hide(1000);
        $("#divtrabajosChoryC2").hide(1000);
        $("#divtrabajosAlexC2").show(1000);
    });





    //conferencias
    $("#menuConferencias").click(function(event){
        $("#")
    })
});